library("MASS")

############### Reversible jump example for a subgroup identification problem #######################
#########       Wentian Guo, Yuan Ji May 2017                                 #######################

### Index: i=1,..., I subgroups;     j=1,...n patients;     s=1,..., S=2 biomarkers

## Assume j=1,... n patients have nx=2 biomarker measurements.
## Assume each biomarker s can be divided by up to G_s=2 values. Where there is one cutoff value, we use c_s | G_s=1 ~ N(mu_1, sigma^2_1) to denote the cutoff. When there are two cutoff values. The smaller one C_sl | G_s = 2 ~ N(mu_1, sigma^2_1) and the larger one is c_sl + c_sg, where c_sg ~ log-Normal(mu_2, sigma^2_2). Given G_1 and G_2, and C's (the cutoff values), we have a partition of the two-dimensional biomarker space. Let I denote the number of subgroups generated by the cutoff values. For a patient, given his/her two biomarker values, he/she will be assigned to a subgroup, denoted by l_j = i, j=1,..., n, and i=1,..., I.

## Assume y_j is thebinary outcome for patient j (such as reponse to a drug). Then assume y_j | {l_j = i, G, C} ~ Bern(theta_i). Let theta_i ~ Beta(a, b)
## Also, Priors: Pr(G_s = 1) = p1, Pr(G_s = 2) = 1-p1


######     ^
######     |         |           |           
######     |  theta1 |  theta4   |  theta7         
######     |         |           |           
######     |         |           |
######     ---------------------------------
######     |         |           |           
######     |  theta2 |  theta5   |  theta8         
######     |         |           |           
######     |         |           |           
######     ---------------------------------
######     |         |           |           
######     |  theta3 |  theta6   |  theta9         
######     |         |           |           
######     |         |           |           
######     ------------------------------------>



########################  ------------------    ##########################
########################      functions         ##########################
########################  ------------------    ########################

########################################################
subnumber=function(x,cl,cg,G){##find the subgroup label for all data x using current cl, cg and G
	subn=rep(0,nrow(x))
	for(j in 1:length(cl)){
		if(G[j]==2) subn=subn+mul(j-1,G+1)*findInterval(x[,j],c(cl[j],cl[j]+cg[j]))
		else subn=subn+mul(j-1,G+1)*findInterval(x[,j],cl[j])
	}
	subn+1
}

########################################################


########################################################
mul=function(i,y){## function that does product of numbers; but takes value 1 when length(y)=0
	if(i==0)ttt=1
	else ttt=prod(y[1:i])
	
	ttt
}
########################################################



########################################################
ratio=function(y,theta,tloc,subn,subnstar,cl,clstar,cg,cgstar,mu1,sigma1,mu2,sigma2,j,lorg){
	##acceptance ratio in metroplis step for cg and cl
	if(lorg=="l"){
		ratio=exp(-sum(y*log(theta[tloc][subn])+(1-y)*log(1-theta[tloc][subn]))+sum(y*log(theta[tloc][subnstar])+(1-y)*log(1-theta[tloc][subnstar]))-((clstar[j]-mu1)^2-(cl[j]-mu1)^2)/(2*sigma1^2))
	}
	if(lorg=="g"){
		ratio=exp(-sum(y*log(theta[tloc][subn])+(1-y)*log(1-theta[tloc][subn]))+sum(y*log(theta[tloc][subnstar])+(1-y)*log(1-theta[tloc][subnstar]))-((log(cgstar[j])-mu2)^2-(log(cg[j])-mu2)^2)/(2*sigma2^2))
			}
	ratio
}

########################################################



########################################################
thetaloc=function(index,nx,G){##locate theta
    index[1]+sum(sapply(2:nx-1,mul,y=G+1)*(index[2:nx]-1))
}

########################################################	
	

########################################################
Gupdate=function(y,subn,theta,tloc,index,cl,cg,G,prior,Gprop,nx){#only delta
	#propose a new G using RJ
    for (j in 1:nx){
		if(runif(1,0,1)<0.5){
			Gnew=G
			Gnew[j]=3-G[j]
			if(G[j]==1){
				clnew=cl
				cgnew=cg
				u=rgamma(1,Gprop$ga,Gprop$gb)
				cgnew[j]=u
				v=rbeta(prod(G[-j]+1),Gprop$ba,Gprop$bb)
				index1=index[order(index[,j]),]
				indexadd=index1[1:(0.5*nrow(index)),]
				index1[which(index1[,j]==2),j]=3
				indexadd[,j]=2
				indexnew=rbind(index1,indexadd)
				tlocnew=apply(indexnew,1,thetaloc,nx,Gnew)
				thetanew=c(theta,v)
				
				subnnew=subnumber(x,clnew,cgnew,Gnew)
				
				Gratio = exp(
                                    sum(y*log(thetanew[order(tlocnew)][subnnew]) +(1-y)*log(1-thetanew[order(tlocnew)][subnnew]))   -sum(y*log(theta[order(tloc)][subn])+(1-y)*log(1-theta[order(tloc)][subn])))                                * prod(dbeta(v,prior$a,prior$b)) * exp(-((clnew[j]-prior$mu1)^2-(cl[j]-prior$mu1)^2)/2/prior$sigma1^2)                                * dlnorm(u,prior$mu2,prior$sigma2)   *p2/p1*ps/(1-ps)               /dgamma(u,Gprop$ga,Gprop$gb)/prod(dbeta(v,Gprop$ba,Gprop$bb))			
				
			}
			
			if(G[j]==2){
				clnew=cl
				cgnew=cg
				u=cg[j]
				index1=index[which(index[,j]!=2),]
				thetanew=theta[which(index[,j]!=2)]
				v=theta[which(index[,j]==2)]
				indexnew=index1
				indexnew[which(index1[,j]==3),j]=2
				tlocnew=apply(indexnew,1,thetaloc,nx,Gnew)
				subnnew=subnumber(x,clnew,cgnew,Gnew)
				
				Gratio=exp(sum(y*log(thetanew[order(tlocnew)][subnnew])+(1-y)*log(1-thetanew[order(tlocnew)][subnnew]))-sum(y*log(theta[order(tloc)][subn])+(1-y)*log(1-theta[order(tloc)][subn])))/prod(dbeta(v,prior$a,prior$b))*exp(-((clnew[j]-prior$mu1)^2-(cl[j]-prior$mu1)^2)/2/prior$sigma1^2)/dlnorm(u,prior$mu2,prior$sigma2)*p1/p2*pm/(1-pm)*dgamma(u,Gprop$ga,Gprop$gb)*prod(dbeta(v,Gprop$ba,Gprop$bb))
				
			}
			
			if (runif(1,0,1)<Gratio){
					cl=clnew
					cg=cgnew
					index=indexnew
					tloc=tlocnew
					theta=thetanew
					subn=subnnew
					G=Gnew
				}
			}
	}
	return(list(cl=cl,cg=cg,index=index,tloc=tloc,theta=theta,subn=subn,G=G))
}

########################################################


########################  ------------------    ##########################
########################      End of functions         ##########################
########################  ------------------    ########################






########################  ------------------    ##########################
########################  Prior parameters         ##########################
########################  ------------------    ########################


mu1=mu2=0
mu4=0
sigma1=2
sigma2=0.5
sigma3=0.05; sigma4=0.05    ## M-H Step for cl and cg
  
a=b=1  ## beta prior for theta
a1=b1=1  ## proposal beta distribution parameters

#w=rep(0.5,nx)

Gprop=list(ga=2,gb=2,ba=1,bb=1)

prior=list(mu1=0,sigma1=10,mu2=0,sigma2=10,a=1,b=1,alpha=1)

ps=0.5
pm=0.5

p1=p2=0.5


########################  ------------------    ##########################
########################   End of Prior paras   ##########################
########################  ------------------    ########################



########################  ------------------    ##########################
########################   True values          ##########################
########################  ------------------    ########################

Nmcmc=2000  ## number of MCMC  iterations
n=1000  ## Number of subjects
nx=2  ## Number of biomarkers
I=3^nx  ## Number of max subgroups with each biomaker having up to two cutoffs

set.seed(100)

# true x and cutoff points
x=matrix(rnorm(n*nx),n,nx)
cut1=c(-0.6,0.6)
cut2=c(-0.6,0.6)
cut=rbind(cut1,cut2)


####   true theta   ######################
# ttheta=c(0.2,0.3,0.8,0.8,0.2,0.8,0.8,0.8,0.3)
# ttheta=c(0.2,0.8,0.8,0.8,0.2,0.8,0.8,0.8,0.3) ###most distinguishable
ttheta=c(0.3,0.7,0.5,0.3,0.7,0.5,0.6,0.2,0.9) ###distinguishable 6 groups
# ttheta=c(0.5,0.8,0.9,0.2,0.4,0.6,0.3,0.5,0.7) ###cannot detect minor difference
# ttheta=c(0.5,0.8,0.9,0.2,0.4,0.7,0.3,0.5,0.6)

####  find the true subgroup for each subject #####
loc=matrix(NA,n,nx)
subnum=rep(0,n)
for(j in 1:nx){
	loc[,j]=findInterval(x[,j],cut[j,]) #### loc[,1] \in {0, 1, 2}, loc[,2] \in {0, 3, 6} ##
	subnum=subnum+3^(j-1)*loc[,j]  ### Here, subnum \in {0, 1, 2, 3, 4, 5, 6, 7, 8}
}
subnum=subnum+1 ### Here, subnum \in {1, 2, 3, 4, 5, 6, 7, 8, 9} are the subgroup lables



##generate true responses
y=rbinom(n,1,ttheta[subnum])

G=rep(2,nx)
cltrue=cut[,1]
cgtrue=cut[,2]-cut[,1]
subntrue=subnumber(x,cltrue,cgtrue,G)


########################  ------------------    ##########################
########################   End of True Values   ##########################
########################  ------------------    ########################


########################  ------------------    ##########################
########################  Start Values          ##########################
########################  ------------------    ########################

#### Both biomarkers have two cutoff values (0, 2). THis leads to 9 subgroups
cl=rep(0,2)
cg=rep(2,2)

subn=subnumber(x,cl,cg,G)  ### Initial subgroup labels

theta=rep(0.5,9)  ### Initial theta estimates for 9 subgroups. 

index=matrix(c(rep(1:3,3),rep(1:3,rep(3,3))),9,2)   ### This is the two-dimensional index of the subgroups (i, j), i=1,2,3, j=1,2,3
tloc=apply(index,1,thetaloc,nx,G)  ### Function thetaloc() converts the two dimentional index to one-dimensional index 1 - 9 for the subgroups


########################  ------------------    ##########################
########################  End of Start Value    ##########################
########################  ------------------    ########################


########################  ------------------    ##########################
########################  MCMC                  ##########################
########################  ------------------    ########################


Theta=matrix(NA,Nmcmc,I)
C=matrix(NA,Nmcmc,2*nx)
Gseq=matrix(NA,Nmcmc,nx)
Index=vector("list",Nmcmc)
Tloc=matrix(NA,Nmcmc,I)
Logp=rep(NA, Nmcmc)

time=proc.time()
for (it in 1:Nmcmc){  ### MCMC iteration	
	for (j in 1:nx){  ### biomarker iteration

       #### M-H on (cl, cg), the two cutoff ratios for each biomarker; No Riversible jumps yet. 
		clstar=cl
		cgstar=cg
		clstar[j]=rnorm(1,cl[j],sigma3)
		subnstar=subnumber(x,clstar,cgstar,G)
                
		accrat=ratio(y,theta,tloc,subn,subnstar,cl,clstar,cg,cgstar,mu1,sigma1,mu2,sigma2,j,"l")		

		if (runif(1,0,1)<accrat) {
			cl=clstar
			cg=cgstar
			subn=subnstar
		}
		


		if (G[j]==2){
			clstar=cl
			cgstar=cg
			cgstar[j]=exp(rnorm(1,log(cg[j]),sigma4))
			subnstar=subnumber(x,clstar,cgstar,G)
			accrat=ratio(y,theta,tloc,subn,subnstar,cl,clstar,cg,cgstar,mu1,sigma1,mu2,sigma2,j,"g")
	
		
			if (runif(1,0,1)<accrat) {
				cl=clstar
				cg=cgstar
				subn=subnstar
			}
			
		}

	}
      ##################### End of M-H on (cl, cg)   ##################################################	
	

      ############ Gibbs step on the theta's    ##################################################	

	for (i in 1:prod(G+1)){
		
		theta[i]=rbeta(1,a+sum(y[subn==tloc[i]]),b+length(y[subn==tloc[i]])-sum(y[subn==tloc[i]]))
	}
	
      ############ End of Gibbs step on the theta's    ##################################################

        
      ############ Calculation of log-posterior (for convergence checking)    ##################################################

        C[it,]=c(cl,cg)
	Gseq[it,]=G
	
	Theta[it,1:length(theta)]=theta[order(tloc)]
	 Tloc[it,1:length(tloc)]=tloc
	 logp=sum(y*log(theta[order(tloc)][subn])+(1-y)*log(1-theta[order(tloc)][subn]))+sum(log(dbeta(theta,prior$a,prior$b)))-sum((cl-prior$mu1)^2/2/prior$sigma1^2)+sum(log(dlnorm(cg[which(G==2)],prior$mu2,prior$sigma2)))+log(p1)
	
        Logp[it]=logp
        
      ############ End of Calculation of log-posterior (for convergence checking)    ##################################################

	
      ########### Begin reversible jump on G ###########################
	Gu=Gupdate(y,subn,theta,tloc,index,cl,cg,G,prior,Gprop,nx)
	if(sum(G!=Gu$G)>0) {
		theta=Gu$theta
		tloc=Gu$tloc
		index=Gu$index
		cl=Gu$cl
		cg=Gu$cg
		G=Gu$G
		subn=subnumber(x,cl,cg,G)
		label=rank(theta,ties.method="min")
	}

      ########### End reversible jump on G ###########################

	
	
	 print(it)
	
	
	
}

# assign("last.warning", NULL, envir = baseenv())

proc.time()-time

plot(1:Nmcmc,Logp,"l")
par(mfrow=c(2,2))
plot(1:Nmcmc,C[1:Nmcmc,1],"l")
plot(1:Nmcmc,C[1:Nmcmc,2],"l")
plot(1:Nmcmc,C[1:Nmcmc,3],"l")
plot(1:Nmcmc,C[1:Nmcmc,4],"l")


par(mfrow=c(3,3))
plot(1:Nmcmc,Theta[1:Nmcmc,1],"l")
plot(1:Nmcmc,Theta[1:Nmcmc,2],"l")
plot(1:Nmcmc,Theta[1:Nmcmc,3],"l")
plot(1:Nmcmc,Theta[1:Nmcmc,4],"l")
plot(1:Nmcmc,Theta[1:Nmcmc,5],"l")
plot(1:Nmcmc,Theta[1:Nmcmc,6],"l")
plot(1:Nmcmc,Theta[1:Nmcmc,7],"l")
plot(1:Nmcmc,Theta[1:Nmcmc,8],"l")
plot(1:Nmcmc,Theta[1:Nmcmc,9],"l")
